name: Check

on:
  push:

jobs:
  tsc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tsc
        run: npx tsc

      - name: Run tsc for tests
        if: hashFiles('functions/tests/tsconfig.json') != ''
        run: npx tsc --project tests/tsconfig.json

  type-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run type-coverage
        run: npx type-coverage

      - name: Run type-coverage for tests
        if: hashFiles('functions/tests/tsconfig.json') != ''
        run: npx type-coverage --project tests/tsconfig.json
